<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="40221" started-at="2020-07-04T03:27:50Z" finished-at="2020-07-04T03:28:30Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="40221" started-at="2020-07-04T03:27:50Z" finished-at="2020-07-04T03:28:30Z">
      <class name="regression.testscripts.ValidateLogin2">
        <test-method status="PASS" signature="setUp()[pri:0, instance:regression.testscripts.ValidateLogin2@6950e31]" name="setUp" is-config="true" duration-ms="9421" started-at="2020-07-04T03:27:50Z" finished-at="2020-07-04T03:28:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateLoginTest(java.lang.String, java.lang.String)[pri:0, instance:regression.testscripts.ValidateLogin2@6950e31]" name="validateLoginTest" duration-ms="6205" started-at="2020-07-04T03:28:00Z" data-provider="getData" finished-at="2020-07-04T03:28:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qshore]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qshore123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:regression.testscripts.ValidateLogin2@6950e31]" name="teardown" is-config="true" duration-ms="7264" started-at="2020-07-04T03:28:06Z" finished-at="2020-07-04T03:28:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:regression.testscripts.ValidateLogin2@6950e31]" name="setUp" is-config="true" duration-ms="6587" started-at="2020-07-04T03:28:13Z" finished-at="2020-07-04T03:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateLoginTest(java.lang.String, java.lang.String)[pri:0, instance:regression.testscripts.ValidateLogin2@6950e31]" name="validateLoginTest" duration-ms="3433" started-at="2020-07-04T03:28:20Z" data-provider="getData" finished-at="2020-07-04T03:28:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[reyaz]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[reyaz123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regression.testscripts.ValidateLogin2.validateLoginTest(ValidateLogin2.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:regression.testscripts.ValidateLogin2@6950e31]" name="teardown" is-config="true" duration-ms="6806" started-at="2020-07-04T03:28:23Z" finished-at="2020-07-04T03:28:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- regression.testscripts.ValidateLogin2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
